server.port=9091
spring.datasource.url=jdbc:postgresql://localhost:5432/statDB
spring.datasource.username=dbuser
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.format_sql=true
spring.sql.init.mode=always