server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5433/ewmDB
spring.datasource.username=ewmuser
spring.datasource.password=12345
spring.datasource.driverClassName=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.format_sql=true
spring.sql.init.mode=always
spring.jpa.properties.hibernate.default_batch_fetch_size=16